#!/usr/bin/env python3
"""Materialize a schema-valid SWR lane decision from real local command evidence."""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Any


SECRET_RE = re.compile(
    r"(?i)(access_token|refresh_token|mood_token|x-mood-token|client_secret|password|authorization|api[_-]?key)"
    r"([\"']?\s*[:=]\s*[\"']?)([^\"'\s,}]{8,})"
)


def now_iso() -> str:
    return datetime.now().astimezone().isoformat(timespec="seconds")


def slug_ts() -> str:
    return datetime.now().astimezone().strftime("%Y%m%dT%H%M%S%z")


def redact(text: str) -> str:
    return SECRET_RE.sub(r"\1\2[REDACTED]", text)


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        return default
    return json.loads(text)


def write_json_atomic(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    os.replace(tmp, path)


def run_command(root: Path, argv: list[str]) -> dict[str, Any]:
    proc = subprocess.run(
        argv,
        cwd=root,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    return {
        "command": " ".join(argv),
        "exit_code": proc.returncode,
        "stdout_tail": redact(proc.stdout[-2000:]),
        "stderr_tail": redact(proc.stderr[-2000:]),
    }


def command_plan(slice_id: str) -> list[list[str]]:
    commands = [
        ["python", "-m", "ops.autonomy.autokeel", "--doctor", "--strict-swr", slice_id],
        ["python", "scripts/check_no_tracked_data.py", "--json"],
        ["python", "scripts/verify_failure_ledger.py", "--json"],
    ]
    if slice_id == "S05":
        commands.insert(1, ["python", "scripts/verify_s05_provider_policy.py", "--json"])
    return commands


def materialize(root: Path, slice_id: str) -> dict[str, Any]:
    root = root.resolve()
    slices_path = root / "ops/autonomy/slices.json"
    slices = load_json(slices_path, [])
    if not isinstance(slices, list):
        return {"status": "error", "errors": ["ops/autonomy/slices.json must contain a list"]}

    target = next((item for item in slices if isinstance(item, dict) and item.get("id") == slice_id), None)
    if not isinstance(target, dict):
        return {"status": "error", "errors": [f"unknown slice: {slice_id}"]}

    errors: list[str] = []
    if target.get("lane") != "swr_preferred":
        errors.append(f"{slice_id} is not swr_preferred")
    if target.get("risk") != "high":
        errors.append(f"{slice_id} is not high risk")

    review_artifacts = target.get("review_artifacts")
    if not isinstance(review_artifacts, list) or len(review_artifacts) < 2:
        errors.append(f"{slice_id} requires at least two review_artifacts for a high-risk SWR lane decision")

    if errors:
        return {"status": "error", "errors": errors}

    command_results = [run_command(root, argv) for argv in command_plan(slice_id)]
    failed = [row for row in command_results if row["exit_code"] != 0]
    if failed:
        return {
            "status": "error",
            "errors": [f"lane-decision prerequisite failed: {row['command']}" for row in failed],
            "commands": command_results,
        }

    decision_dir = root / "ops/autonomy/decisions"
    decision_path = decision_dir / f"{slice_id}-lane-decision-{slug_ts()}.json"
    decision_payload = {
        "created_at": now_iso(),
        "status": "accepted",
        "slice": slice_id,
        "lane": "swr_preferred",
        "decision": "use_swr",
        "risk": "high",
        "reason": (
            "High-risk swr_preferred slice must be generated by keel-swr. "
            "This decision was materialized only after strict SWR provider preflight, "
            "slice provider-policy preflight, tracked-data hygiene, and failure-ledger checks passed."
        ),
        "review_artifacts": review_artifacts,
        "commands": command_results,
        "verdict": "pass",
    }
    write_json_atomic(decision_path, decision_payload)

    target["lane_decision"] = str(decision_path.relative_to(root))
    target["updated_at"] = now_iso()
    write_json_atomic(slices_path, slices)

    return {
        "status": "ok",
        "slice": slice_id,
        "lane_decision": str(decision_path.relative_to(root)),
        "commands": command_results,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Create a reviewed SWR lane decision from real command evidence.")
    parser.add_argument("slice_id")
    parser.add_argument("--root", default=".")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)

    report = materialize(Path(args.root), args.slice_id.upper())
    if args.json:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        for error in report.get("errors", []):
            print(f"ERROR: {error}", file=sys.stderr)
        print(report["status"])
    return 0 if report["status"] == "ok" else 1


if __name__ == "__main__":
    raise SystemExit(main())
